                                                                                                                                                                                   
from usuarios.models import Usuario                                                                                                                                                                               
                                                                                                                                                                                                                    
usuarios = [                                                                                                                                                                                                      
      ('luisa.lozano', 'Luisa Fernanda', 'Lozano', 'mafe-juanjo17@hotmail.com'),                                                                                                                                    
      ('angelica.cardozo', 'Angelica Maria', 'Cardozo Pacheco', 'amcardozopac@gmai.com'),                                                                                                                           
      ('karla.mendez', 'Karla Juanita', 'Mendez Avendaño', 'cochilestez@gmail.com'),                                                                                                                                
      ('heidy.mendez', 'Heidy Leonela', 'Mendez Elizalde', 'nonamendez819@gmail.com'),                                                                                                                              
      ('liliana.gonzales', 'Liliana', 'Gonzales Sierra', 'lilianalucas10@hotmail.com'),                                                                                                                             
      ('edna.mendez', 'Edna Julieth', 'Mendez Carvajal', 'mendezyulieth18@gmail.com'),                                                                                                                              
      ('alejandra.ramos', 'Alejandra', 'Ramos Roa', 'alejandraramosroa@gmail.com'),                                                                                                                                 
      ('edwin.gutierrez', 'Edwin Fernando', 'Gutierrez Reyes', 'edwinho94@gmail.com'),                                                                                                                              
      ('laura.galindo', 'Laura Fernanda', 'Galindo Jaramillo', 'lauragalindojaramillo@gmail.com'),                                                                                                                  
      ('monica.romero', 'Monica Alexandra', 'Romero Ramirez', 'monicaromero11@hotmail.es'),                                                                                                                         
      ('yarima.lizcano', 'Yarima Fernanda', 'Lizcano Medina', 'yarimamedina31@gmail.com'),                                                                                                                          
      ('mabel.osorio', 'Mabel Zoraida', 'Osorio Hernandez', 'juridico.oh@outlook.es'),                                                                                                                              
      ('rosario.romero', 'Rosario Del Pilar', 'Romero', 'charitodelpilar@hotmail.com'),                                                                                                                             
      ('jhon.agudelo', 'Jhon Edward', 'Agudelo Orjuela', 'jhonedwardao@gmail.com'),                                                                                                                                 
      ('diego.acosta', 'Diego Fernando', 'Acosta Hollos', 'diefer8@hotmail.com'),                                                                                                                                   
  ]                                                                                                                                                                                                                 
                                                                                                                                                                                                                    
for username, first_name, last_name, email in usuarios:                                                                                                                                                           
      u = Usuario.objects.create_user(                                                                                                                                                                              
          username=username,                                                                                                                                                                                        
          email=email,                                                                                                                                                                                              
          password='pulsar',                                                                                                                                                                                        
          first_name=first_name,                                                                                                                                                                                    
          last_name=last_name,                                                                                                                                                                                      
      )                                                                                                                                                                                                             
      print(f'Creado: {u.username} - {u.email}')                                                                                                                                                                    
                                                                                                                                                                                                                    
print(f'\nTotal: {len(usuarios)} usuarios creados')                                                                                                                                                                                                                                                       