# Generated by Django 5.0 on 2026-02-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(default='Sin titulo', max_length=100),
        ),
    ]
