# Generated by Django 5.0 on 2026-02-17 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes_entrada', models.TimeField(default='07:00')),
                ('lunes_salida', models.TimeField(default='16:00')),
                ('martes_entrada', models.TimeField(default='07:00')),
                ('martes_salida', models.TimeField(default='16:00')),
                ('miercoles_entrada', models.TimeField(default='07:00')),
                ('miercoles_salida', models.TimeField(default='16:00')),
                ('jueves_entrada', models.TimeField(default='07:00')),
                ('jueves_salida', models.TimeField(default='16:00')),
                ('viernes_entrada', models.TimeField(default='07:00')),
                ('viernes_salida', models.TimeField(default='16:00')),
                ('sabado_entrada', models.TimeField(default='07:00')),
                ('sabado_salida', models.TimeField(default='12:00')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario_laboral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario Laboral',
                'verbose_name_plural': 'Horarios Laborales',
            },
        ),
    ]
