# Generated by Django 5.0 on 2026-03-19 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_crear_horarios_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariolaboral',
            name='jueves_entrada_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='jueves_salida_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='lunes_entrada_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='lunes_salida_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='martes_entrada_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='martes_salida_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='miercoles_entrada_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='miercoles_salida_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='sabado_entrada_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='sabado_salida_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='viernes_entrada_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='viernes_salida_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='jueves_entrada',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='jueves_salida',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='lunes_entrada',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='lunes_salida',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='martes_entrada',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='martes_salida',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='miercoles_entrada',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='miercoles_salida',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='sabado_entrada',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='sabado_salida',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='viernes_entrada',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='viernes_salida',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
